# Code generated by kickr; DO NOT EDIT.

.PHONY: clean
clean:
	@go clean
	@git clean -dfX

GOCI_LINT_PATH ?= .golangci.yml

.PHONY: lint
lint:
	@golangci-lint run --config=${GOCI_LINT_PATH} --timeout=240s --allow-parallel-runners \
		--output.text.path=stdout $(ARGS) || \
		echo "golangci-lint failed, running 'make lint-fix' may fix some issues"

.PHONY: lint-fix
lint-fix:
	@ARGS="--fix" make -s lint

.PHONY: test
test:
	@go test ./... -count 1 -timeout=30s

.PHONY: test-race
test-race:
	@CGO_ENABLED=1 go test ./... -race -timeout=30s

.PHONY: test-cover
test-cover:
	@go test ./... -v -coverpkg="./..." -covermode="count" -timeout=30s
